apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --url
            - http://caddy-private:80
---
apiVersion: v1
kind: Service
metadata:
  name: dockge
  labels:
    app: dockge
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: dockge
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockge-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockge
  labels:
    app: dockge
spec:
  selector:
    matchLabels:
      app: dockge
  template:
    metadata:
      labels:
        app: dockge
    spec:
      containers:
        - name: dockge
          image: louislam/dockge:latest
          env:
            - name: DOCKGE_STACKS_PATH
              value: /opt/stacks
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: dockge-data
              mountPath: /app/data
            - name: stacks
              mountPath: /opt/stacks
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: dockge-data
          persistentVolumeClaim:
            claimName: dockge-pvc
        - name: stacks
          hostPath:
            path: /opt/stacks
            type: DirectoryOrCreate
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dockge-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - dockge.localhost
      secretName: localhost-tls
  rules:
    - host: dockge.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dockge
                port:
                  number: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - minikube.localhost
      secretName: localhost-tls
  rules:
    - host: minikube.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 80
